version: "3.7"

services:
  camera_service:
    build: ./camera-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./camera-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  flood_information_service:
    build: ./flood-information-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./flood-information-service/:/app/
    ports:
      - 8003:8000
  notifications_service:
    build: ./notification-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./notification-service/:/app/
    ports:
      - 8004:8000

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - camera_service
      - flood_information_service
      - notifications_service

volumes:
  postgres_data_movie:
  postgres_data_cast:
  postgres_data_auth:
